apiVersion: v1
kind: ResourceQuota
metadata:
  name: store-quota
  namespace: store-demo
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
    persistentvolumeclaims: "2"
    requests.storage: "2Gi"
