apiVersion: v1
kind: LimitRange
metadata:
  name: store-limitrange
  namespace: store-demo
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "200m"
      memory: "256Mi"
