apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: store-default-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - namespaceSelector: {}
  
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # Allow same-namespace communication (WordPress <-> MySQL)
    - to:
        - podSelector: {}
    # Allow outbound HTTPS (for WooCommerce download)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
