apiVersion: v1
kind: Secret
metadata:
  name: store-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}

  WP_ADMIN_USER: {{ .Values.store.adminUser | quote }}
  WP_ADMIN_PASSWORD: {{ .Values.store.adminPassword | quote }}
  WP_ADMIN_EMAIL: {{ .Values.store.adminEmail | quote }}
